const TARGETS_TOTAL=24,ARROWS_PER_TARGET=2,CURRENT_KEY="bosco3d-lite-current-v13",HISTORY_KEY="bosco3d-lite-history-v13";
const $=id=>document.getElementById(id);
const screens={home:$("home"),training:$("training"),summary:$("summary"),history:$("history")};
const el={btnNew:$("btnNew"),btnResume:$("btnResume"),btnHistory:$("btnHistory"),btnUndo:$("btnUndo"),btnCancel:$("btnCancel"),btnSaveResult:$("btnSaveResult"),btnAgain:$("btnAgain"),btnHome:$("btnHome"),btnHistoryHome:$("btnHistoryHome"),btnClearHistory:$("btnClearHistory"),btnBackHomeSmall:$("btnBackHomeSmall"),btnSummaryBack:$("btnSummaryBack"),notes:$("trainingNotes"),target:$("targetNumber"),arrow:$("arrowNumber"),total:$("total"),finalTotal:$("finalTotal"),summaryDate:$("summaryDate"),summaryNotes:$("summaryNotes"),summaryStats:$("summaryStats"),targetDetails:$("targetDetails"),historyList:$("historyList"),scoreButtons:document.querySelectorAll(".score")};
let training=null;
function nowIso(){return new Date().toISOString()}function fmt(i){return new Date(i).toLocaleString("it-IT",{dateStyle:"short",timeStyle:"short"})}function clone(x){return JSON.parse(JSON.stringify(x))}function esc(t){return String(t||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function uid(){return String(Date.now())+"-"+Math.random().toString(16).slice(2)}
function newTraining(){return{id:uid(),startedAt:nowIso(),endedAt:null,notes:el.notes.value.trim(),currentTarget:1,currentArrow:1,total:0,finished:false,saved:false,targets:Array.from({length:TARGETS_TOTAL},(_,i)=>({number:i+1,arrows:[]})),undoStack:[]}}
function show(n){Object.values(screens).forEach(s=>s.classList.remove("active"));screens[n].classList.add("active");if(n==="home")updateResume()}
function saveCurrent(){if(training)localStorage.setItem(CURRENT_KEY,JSON.stringify(training))}function loadCurrent(){try{const t=JSON.parse(localStorage.getItem(CURRENT_KEY));if(!t||!Array.isArray(t.targets))return null;if(!Array.isArray(t.undoStack))t.undoStack=[];if(typeof t.notes!=="string")t.notes="";return t}catch{return null}}function clearCurrent(){localStorage.removeItem(CURRENT_KEY)}function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY))||[]}catch{return[]}}function saveHistory(list){localStorage.setItem(HISTORY_KEY,JSON.stringify(list))}function updateResume(){const s=loadCurrent();el.btnResume.classList.toggle("hidden",!s||s.finished)}
function startTraining(){const s=loadCurrent();if(s&&!s.finished&&!confirm("C'è già un allenamento in corso. Vuoi sostituirlo?"))return;training=newTraining();saveCurrent();updateUI();show("training")}function resumeTraining(){const s=loadCurrent();if(!s)return;training=s;if(training.finished){renderSummary();show("summary")}else{updateUI();show("training")}}function updateUI(){if(!training)return;el.target.textContent=`${training.currentTarget} / ${TARGETS_TOTAL}`;el.arrow.textContent=`${training.currentArrow} / ${ARROWS_PER_TARGET}`;el.total.textContent=training.total}
function addScore(score){if(!training||training.finished)return;training.undoStack.push(clone({currentTarget:training.currentTarget,currentArrow:training.currentArrow,total:training.total,finished:training.finished,targets:training.targets}));training.targets[training.currentTarget-1].arrows[training.currentArrow-1]=score;training.total+=score;if(navigator.vibrate)navigator.vibrate(25);if(training.currentArrow<ARROWS_PER_TARGET){training.currentArrow++}else{training.currentArrow=1;training.currentTarget++}if(training.currentTarget>TARGETS_TOTAL){training.finished=true;training.endedAt=nowIso();saveCurrent();renderSummary();show("summary");return}saveCurrent();updateUI()}
function undoLast(){if(!training||!training.undoStack.length)return;const p=training.undoStack.pop(),stack=training.undoStack;training={...training,currentTarget:p.currentTarget,currentArrow:p.currentArrow,total:p.total,finished:p.finished,targets:p.targets,undoStack:stack};saveCurrent();updateUI();show("training")}function cancelTraining(){if(!training){show("home");return}if(!confirm("Vuoi davvero annullare l'allenamento in corso?"))return;training=null;clearCurrent();show("home")}
function countsFor(t){const c={11:0,10:0,8:0,5:0,0:0};t.targets.forEach(g=>g.arrows.forEach(s=>{if(s===11)c[11]++;else if(s===10)c[10]++;else if(s===8)c[8]++;else if(s===5)c[5]++;else if(s===0)c[0]++}));return c}function tt(g){return g.arrows.reduce((a,b)=>a+(b||0),0)}function at(v){return v==null?"—":v===0?"M":String(v)}function badges(c){return `<div class="badge b11">11<small>${c[11]}</small></div><div class="badge b10">10<small>${c[10]}</small></div><div class="badge b8">8<small>${c[8]}</small></div><div class="badge b5">5<small>${c[5]}</small></div><div class="badge bm">M<small>${c[0]}</small></div>`}
function renderTargets(container,t){container.innerHTML=t.targets.map(g=>`<div class="target-row"><span>Piazzola ${g.number}</span><span>${at(g.arrows[0])} + ${at(g.arrows[1])}</span><strong>${tt(g)}</strong></div>`).join("")}
function renderSummary(){if(!training)return;if(!training.endedAt)training.endedAt=nowIso();const c=countsFor(training);el.finalTotal.textContent=training.total;el.summaryDate.textContent=fmt(training.endedAt);el.summaryStats.innerHTML=badges(c);if(training.notes){el.summaryNotes.classList.remove("hidden");el.summaryNotes.innerHTML=`<b>Note:</b><br>${esc(training.notes)}`}else{el.summaryNotes.classList.add("hidden");el.summaryNotes.innerHTML=""}renderTargets(el.targetDetails,training);el.btnSaveResult.textContent=training.saved?"✅ Risultato salvato":"💾 Salva risultato"}
function saveResult(){if(!training||!training.finished||training.saved)return;const h=loadHistory(),item=clone(training);item.savedAt=nowIso();item.saved=true;h.unshift(item);saveHistory(h);training.saved=true;saveCurrent();renderSummary()}
function deleteHistoryItem(id){const h=loadHistory(),item=h.find(x=>x.id===id);if(!item)return;if(!confirm(`Eliminare l'allenamento da ${item.total} punti del ${fmt(item.endedAt||item.savedAt||item.startedAt)}?`))return;saveHistory(h.filter(x=>x.id!==id));renderHistory()}
function renderHistory(){const h=loadHistory();if(!h.length){el.historyList.innerHTML=`<div class="history-card">Nessun allenamento salvato.</div>`;show("history");return}el.historyList.innerHTML=h.map(item=>{const c=countsFor(item),note=item.notes?`<div class="note">Note: ${esc(item.notes)}</div>`:"",det=item.targets.map(g=>`<div class="target-row"><span>P${g.number}</span><span>${at(g.arrows[0])} + ${at(g.arrows[1])}</span><strong>${tt(g)}</strong></div>`).join("");return `<article class="history-card"><div class="date">${fmt(item.endedAt||item.savedAt||item.startedAt)}</div><div class="points">${item.total} punti</div><div class="score-badges">${badges(c)}</div>${note}<details><summary>Dettaglio piazzole</summary>${det}</details><button class="delete-one" data-delete-id="${item.id}">🗑 Elimina questo allenamento</button></article>`}).join("");document.querySelectorAll("[data-delete-id]").forEach(b=>b.onclick=()=>deleteHistoryItem(b.dataset.deleteId));show("history")}
function clearHistory(){if(!confirm("Vuoi cancellare tutto lo storico?"))return;saveHistory([]);renderHistory()}
function bind(){el.btnNew.onclick=startTraining;el.btnResume.onclick=resumeTraining;el.btnHistory.onclick=renderHistory;el.btnUndo.onclick=undoLast;el.btnCancel.onclick=cancelTraining;el.btnSaveResult.onclick=saveResult;el.btnAgain.onclick=()=>{clearCurrent();el.notes.value="";training=newTraining();saveCurrent();updateUI();show("training")};el.btnHome.onclick=()=>show("home");el.btnHistoryHome.onclick=()=>show("home");el.btnBackHomeSmall.onclick=()=>show("home");el.btnSummaryBack.onclick=()=>show("home");el.btnClearHistory.onclick=clearHistory;el.scoreButtons.forEach(b=>b.onclick=()=>addScore(Number(b.dataset.score)));window.addEventListener("beforeunload",saveCurrent)}
function registerSW(){if(!("serviceWorker" in navigator))return;window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}
bind();updateResume();show("home");registerSW();
