const TARGETS_TOTAL=24,ARROWS_PER_TARGET=2,CURRENT_KEY="bosco3d-lite-current-v12",HISTORY_KEY="bosco3d-lite-history-v12";
const $=id=>document.getElementById(id);
const screens={home:$("home"),training:$("training"),summary:$("summary"),history:$("history")};
const el={btnNew:$("btnNew"),btnResume:$("btnResume"),btnHistory:$("btnHistory"),btnUndo:$("btnUndo"),btnCancel:$("btnCancel"),btnSaveResult:$("btnSaveResult"),btnAgain:$("btnAgain"),btnHome:$("btnHome"),btnHistoryHome:$("btnHistoryHome"),btnClearHistory:$("btnClearHistory"),notes:$("trainingNotes"),target:$("targetNumber"),arrow:$("arrowNumber"),total:$("total"),finalTotal:$("finalTotal"),summaryDate:$("summaryDate"),summaryNotes:$("summaryNotes"),summaryStats:$("summaryStats"),targetDetails:$("targetDetails"),historyList:$("historyList"),scoreButtons:document.querySelectorAll(".score")};
let training=null;
function nowIso(){return new Date().toISOString()}function fmt(i){return new Date(i).toLocaleString("it-IT",{dateStyle:"short",timeStyle:"short"})}function clone(x){return JSON.parse(JSON.stringify(x))}function esc(t){return String(t||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function newTraining(){return{id:String(Date.now()),startedAt:nowIso(),endedAt:null,notes:el.notes.value.trim(),currentTarget:1,currentArrow:1,total:0,finished:false,saved:false,targets:Array.from({length:TARGETS_TOTAL},(_,i)=>({number:i+1,arrows:[]})),undoStack:[]}}
function show(n){Object.values(screens).forEach(s=>s.classList.remove("active"));screens[n].classList.add("active");if(n==="home")updateResume()}
function saveCurrent(){if(training)localStorage.setItem(CURRENT_KEY,JSON.stringify(training))}function loadCurrent(){try{let t=JSON.parse(localStorage.getItem(CURRENT_KEY));if(!t||!Array.isArray(t.targets))return null;if(!Array.isArray(t.undoStack))t.undoStack=[];if(typeof t.notes!=="string")t.notes="";return t}catch{return null}}function clearCurrent(){localStorage.removeItem(CURRENT_KEY)}function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY))||[]}catch{return[]}}function saveHistory(l){localStorage.setItem(HISTORY_KEY,JSON.stringify(l))}function updateResume(){let s=loadCurrent();el.btnResume.classList.toggle("hidden",!s||s.finished)}
function startTraining(){let s=loadCurrent();if(s&&!s.finished&&!confirm("C'è già un allenamento in corso. Vuoi sostituirlo?"))return;training=newTraining();saveCurrent();updateUI();show("training")}
function resumeTraining(){let s=loadCurrent();if(!s)return;training=s;if(training.finished){renderSummary();show("summary")}else{updateUI();show("training")}}
function updateUI(){if(!training)return;el.target.textContent=`${training.currentTarget} / ${TARGETS_TOTAL}`;el.arrow.textContent=`${training.currentArrow} / ${ARROWS_PER_TARGET}`;el.total.textContent=training.total}
function addScore(score){if(!training||training.finished)return;training.undoStack.push(clone({currentTarget:training.currentTarget,currentArrow:training.currentArrow,total:training.total,finished:training.finished,targets:training.targets}));training.targets[training.currentTarget-1].arrows[training.currentArrow-1]=score;training.total+=score;if(navigator.vibrate)navigator.vibrate(25);if(training.currentArrow<ARROWS_PER_TARGET)training.currentArrow++;else{training.currentArrow=1;training.currentTarget++}if(training.currentTarget>TARGETS_TOTAL){training.finished=true;training.endedAt=nowIso();saveCurrent();renderSummary();show("summary");return}saveCurrent();updateUI()}
function undoLast(){if(!training||!training.undoStack.length)return;let p=training.undoStack.pop(),stack=training.undoStack;training={...training,currentTarget:p.currentTarget,currentArrow:p.currentArrow,total:p.total,finished:p.finished,targets:p.targets,undoStack:stack};saveCurrent();updateUI();show("training")}
function cancelTraining(){if(!training){show("home");return}if(!confirm("Vuoi davvero annullare l'allenamento in corso?"))return;training=null;clearCurrent();show("home")}
function countsFor(t){let c={11:0,10:0,8:0,5:0,0:0};t.targets.forEach(g=>g.arrows.forEach(s=>{if(s===11)c[11]++;else if(s===10)c[10]++;else if(s===8)c[8]++;else if(s===5)c[5]++;else if(s===0)c[0]++}));return c}function tt(g){return g.arrows.reduce((a,b)=>a+(b||0),0)}function at(v){return v==null?"—":v===0?"M":String(v)}
function renderTargets(container,t){container.innerHTML=t.targets.map(g=>`<div class="target-row"><span>Piazzola ${g.number}</span><span>${at(g.arrows[0])} + ${at(g.arrows[1])}</span><strong>${tt(g)}</strong></div>`).join("")}
function renderSummary(){if(!training)return;if(!training.endedAt)training.endedAt=nowIso();let c=countsFor(training);el.finalTotal.textContent=training.total;el.summaryDate.textContent=fmt(training.endedAt);el.summaryStats.innerHTML=`<div>11: ${c[11]} · 10: ${c[10]}</div><div>8: ${c[8]} · 5: ${c[5]} · M: ${c[0]}</div>`;if(training.notes){el.summaryNotes.classList.remove("hidden");el.summaryNotes.innerHTML=`<b>Annotazioni:</b><br>${esc(training.notes)}`}else{el.summaryNotes.classList.add("hidden");el.summaryNotes.innerHTML=""}renderTargets(el.targetDetails,training);el.btnSaveResult.textContent=training.saved?"✅ Risultato salvato":"💾 Salva risultato"}
function saveResult(){if(!training||!training.finished||training.saved)return;let h=loadHistory(),item=clone(training);item.savedAt=nowIso();item.saved=true;h.unshift(item);saveHistory(h);training.saved=true;saveCurrent();renderSummary()}
function renderHistory(){let h=loadHistory();if(!h.length){el.historyList.innerHTML='<div class="history-card">Nessun allenamento salvato.</div>';show("history");return}el.historyList.innerHTML=h.map(item=>{let c=countsFor(item),note=item.notes?`<div class="note">${esc(item.notes)}</div>`:"",det=item.targets.map(g=>`<div class="target-row"><span>P${g.number}</span><span>${at(g.arrows[0])} + ${at(g.arrows[1])}</span><strong>${tt(g)}</strong></div>`).join("");return `<article class="history-card"><div class="date">${fmt(item.endedAt||item.savedAt||item.startedAt)}</div><strong>${item.total} punti</strong><div>11: ${c[11]} · 10: ${c[10]} · 8: ${c[8]} · 5: ${c[5]} · M: ${c[0]}</div>${note}<details><summary>Dettaglio piazzole</summary>${det}</details></article>`}).join("");show("history")}
function clearHistory(){if(!confirm("Vuoi cancellare tutto lo storico?"))return;saveHistory([]);renderHistory()}
function bind(){el.btnNew.onclick=startTraining;el.btnResume.onclick=resumeTraining;el.btnHistory.onclick=renderHistory;el.btnUndo.onclick=undoLast;el.btnCancel.onclick=cancelTraining;el.btnSaveResult.onclick=saveResult;el.btnAgain.onclick=()=>{clearCurrent();el.notes.value="";training=newTraining();saveCurrent();updateUI();show("training")};el.btnHome.onclick=()=>show("home");el.btnHistoryHome.onclick=()=>show("home");el.btnClearHistory.onclick=clearHistory;el.scoreButtons.forEach(b=>b.onclick=()=>addScore(Number(b.dataset.score)));window.addEventListener("beforeunload",saveCurrent)}
function registerSW(){if(!("serviceWorker"in navigator))return;window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}
bind();updateResume();show("home");registerSW();
